import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { api } from "@/utils/api";
import { useUser } from "@auth0/nextjs-auth0/client";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { user, error, isLoading } = useUser();

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <Link href="/api/auth/login">Sign In </Link>
        <Link href="/api/auth/logout">Sign Out </Link>
        {user && (
          <div>
            <h1>Hi {user.nickname}!</h1>
            <p>Your email is {user.email}.</p>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
