import { type NextPage } from "next";
import Head from "next/head";
import { api } from "@/utils/api";
import ProductCard from "@/components/product-card";

const Home: NextPage = () => {
  const { data } = api.products.getAll.useQuery();
  return (
    <>
      <Head>
        <title>E-commerce</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white p-4 text-black">
        <h1>Browse All Products</h1>
        <div className="grid grid-cols-1 gap-4 md:grid-cols-3 lg:grid-cols-5">
          {data?.map((product) => (
            <ProductCard
              id={product.id}
              image={product.image}
              name={product.name}
              price={product.price}
              seller={product.userId}
              key={product.id}
              description={product.description}
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
